### ISSUE TITLE
生成域名后缀缺失

### ISSUE THREAD

**Issue by yaoxiaodai** [7dog7/RuleSubDomain#2]
domain输入baidu.com，发现生成的域名字典缺少后缀，```i[:i.rfind(".", 0, i.rfind('.'))]```取值后输出baidu.co缺少m，如下图
![image](https://user-images.githubusercontent.com/28942595/143820614-45a7b192-4d40-463e-b222-04edcc8b2da1.png)

**Comment by 7dog7** [comment]
功能是这样用的，比如www.baidu.com提取www进行字典组合。
